### ISSUE TITLE
How to upload?

### ISSUE THREAD

**Issue by weathon** [Densaugeo/uploadserver#1]
It only shows files but don't allow me upload

**Comment by Densaugeo** [comment]
The index page is served by the underlying http.server, and behaves the same way.

To upload, go to /upload (for example if the server is running at http://localhost:8000/ go to http://localhost:8000/upload ).

**Comment by weathon** [comment]
Oh, OK! Thanks!

**Comment by Densaugeo** [comment]
Clarified instructions in readme 177d6d9

Thanks for reporting the issue.

**Comment by Evidlo** [comment]
I was confused by this also.  Maybe a link to the upload page could be inserted into the directory listing HTML?  This would mean overriding [list_directory()](https://github.com/python/cpython/blob/main/Lib/http/server.py#L777-L832)

**Comment by Densaugeo** [comment]
That would be handy.

I prefer not to replace and take on maintenance for any more of the built-in functions than I have to, but after a closer look it may be possible to create a `.list_directory()` that:
- Calls the original `.list_directory()`
- Inserts some new HTML into the file object returned by the original `.list_directory()` before passing it back
- Iterates over `._headers_buffer` and updates the content-length buffer.

Would also have the benefit of applying dark theme settings to the directory pages.
