### ISSUE TITLE
can't open from IPv4 + feature request: message "upload completed"

### ISSUE THREAD

**Issue by Nesos-ita** [Densaugeo/uploadserver#12]
just installed, first of all, amazing project! i like it, it's super simple and is exactly what i need :)  
for some reason `python -m uploadserver` doesn't work on ipv4 by default, only ipv6 works.  
it doesn't work by going to 127.0.0.1 or if open it from another pc in lan.  
i see that there is "bind option" and using that it works (0.0.0.0).  
both uploadserver and http.server display this at start: `Serving HTTP on :: port 8000 (http://[::]:8000/) ...`  
but http.server works also on ipv4.  
it's a minor issue but it would be nice if you can fix it so that i don't need to add the extra argument bind.  
Python version is: 3.9.0 on windows 10 64bit
i can see that browser is loading while uploading and it stops when finished but a message "upload completed" would be much better.

**Comment by Densaugeo** [comment]
Thanks for the bug report. 2.0.1 should now have the same behavior as http.server. Let me know if there's still an issue.

An upload complete notice for the web page isn't a bad idea, I might add that sometime later. If you have shell access to the server it's running on, the server logs for received files are printed after the upload is complete.

**Comment by marvinruder** [comment]
I proposed an implementation of success messages in #17. Let me know what you think!

**Comment by Densaugeo** [comment]
Reopened, in response to #17 .

**Comment by Densaugeo** [comment]
Upload status added in aca303c465e207068832ca2160443bfecb2e109e

**Comment by Nesos-ita** [comment]
i tested it and it's a very nice to have feature, there is a minor UI update that could improve it and descrease confusion: ensure that the displayed percentage is never 100% since when it's 100% is still uploading (something like if >99% set at 99%) .  
one might read 100% and think it's finished while it's not true since when it's finished it say "Success" (success message is very good), it happened on my first usage, i uploaded a file and it was at 100% and i was thinking is it finished or not? and after a while it changed to "success".

**Comment by Densaugeo** [comment]
A good point. In addition to the rounding issues, after the file is transferred the server also needs a little time to save it to disk. I've updated the status message to better reflect what's going on.
