### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by marioqqq** [Densaugeo/uploadserver#14]
It would be nice to have progress bar. Especially when you need to upload larger files. Because me and my friends use it to upload mods that can have up to 2 GB and even more.  ;) Also authentication to see data wouldn't be bad at all.

**Comment by Densaugeo** [comment]
Wow, that's quite a bit larger than anything I use it for. I might take a look and see if there's an easy way to do it when I get a chance.

There's an authentication option for uploads, but authentication for viewing is beyond the scope of this project. If you really need that, you could run it behind a proxy like Apache that can enforce authentication.

**Comment by marioqqq** [comment]
Okay I will look at that, thanks. Also good luck with the project. It has big potential for some hobbyists like me.
