### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by wlievens** [Densaugeo/uploadserver#15]
I'm trying to use this server from a page with some javascript on it, but I can't get past the CORS checks, because uploadserver doesn't acccept OPTIONS requests. Is it possible to use uploadserver from the browser, e.g. by letting it specify allowed clients on the command line?

**Comment by Densaugeo** [comment]
I haven't done anything with CORS before. Adding a handler for OPTIONS requests shouldn't be hard, and it looks like it might need a Access-Control-Allow-Origin header too (not sure).

If you want to add a handler/CLI option for that I'd be happy to review and merge it.

**Comment by wlievens** [comment]
Sorry, I tried but it seems like I couldn't get it to work. I don't think I know enough about the back-end side of CORS handling to make it properly.

**Comment by Densaugeo** [comment]
Responding to OPTIONS requests isn't enough? Idk much about CORS.

It might be easier if you can get your instance of uploadserver running under the same domain as your page, or put them behind a proxy like Nginx together.

Feel free to reopen this or send a pull request if you do get CORS working.
