### ISSUE TITLE
Multiple files upload

### ISSUE THREAD

**Issue by israhm70** [Densaugeo/uploadserver#2]
I have it all correctly set for single files uploads but I would like to add a choice for multiple files uploads... is that possible with this library? Thank you!

**Comment by Densaugeo** [comment]
It doesn't support multiple files, but I've wanted to do that a couple times myself. I'll leave the issue open and I might get around to adding it eventually.

**Comment by Densaugeo** [comment]
Now supported in 1.0.0, and pushed to PyPI.
