### ISSUE TITLE
How to use upload server for PUT requests

### ISSUE THREAD

**Issue by saimukund** [Densaugeo/uploadserver#21]
linux@linux-ont:~$ python3 -m uploadserver -d upload_py_http/
File upload available at /upload
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
192.168.241.178 - - [25/Aug/2022 11:44:22] code 501, message Unsupported method ('PUT')
192.168.241.178 - - [25/Aug/2022 11:44:22] "PUT /upload HTTP/1.1" 501 -

I am trying to test a feature in my application which needs an upload server. I am using uploadserver for this purpose. The application uses PUT method to upload.  But when I try I am getting unsupported method.
Could you please add support or suggest how to use it for PUT method?

**Comment by Densaugeo** [comment]
Uploadserver uses POST, not PUT. I do not plan to change this.

If you need a server purely for test purposes, I recommend using Python's standard http.server module and extending it with whatever methods your program needs. That's what I do when I need a test server.

If you're looking for a server to handle uploads in production, you should be aware that uploadserver is primarily for small-scale work and has a number of performance limitations.
