### ISSUE TITLE
Unsupported Method: PUT

### ISSUE THREAD

**Issue by theotherguy2175** [Densaugeo/uploadserver#31]
Is put allowed as an http method for this?

Operation not supported: 501 Unsupported method ('PUT') (PUT)

**Comment by Densaugeo** [comment]
PUT is not supported. Uploads are sent using POST, as shown in the examples in the readme.

**Comment by theotherguy2175** [comment]
Is there no way to add this feature? I was trying to use this as a
webserver to upload files from network devices. They use put for this.

**Comment by Densaugeo** [comment]
It would not be too hard to add, though I prefer to avoid adding new API surface unless necessary.

What sort of devices are these that cannot use POST? It seems a little unusual to be able to send PUT but not POST.

**Comment by theotherguy2175** [comment]
Well for one it's Arista and Juniper. They are just using their build in:

copy https://    command.

Which is coded to use put.

**Comment by Densaugeo** [comment]
I see. It looks like adding PUT won't be hard, so I can do that. Will probably get to it this weekend or the one after.
