### ISSUE TITLE
Feature request: add an entry point to support pipx installation

### ISSUE THREAD

**Issue by citreae535** [Densaugeo/uploadserver#35]
[`Pipx`](https://pypa.github.io/pipx/how-pipx-works/#developing-for-pipx) is a tool made specifically for installing pip packages as global applications. It would be nice if `uploadserver` supports this installation method.

The following is the setup script that works on my local fork.
```python
setup(
    # other arguments here...
    entry_points={
        'console_scripts': [
            'uploadserver = uploadserver:main',
        ]
    },
)
```

**Comment by Densaugeo** [comment]
Added this in 5.0.0, but it only works when pipx pulls form GitHub for some reason:
```
[den-antares@gazing-corvid ~]$ python -m pipx run --spec 'git+https://github.com/Densaugeo/uploadserver.git' uploadserver
File upload available at /upload
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

Trying to run from PyPI fails, even though it should be the same package:
```
[den-antares@gazing-corvid ~]$ python -m pipx run uploadserver'uploadserver' executable script not found in package 'uploadserver'.
Available executable scripts:
    
[den-antares@gazing-corvid ~]$
```

Any ideas? I opened a thread over at pipx's GtiHub as well.

**Comment by Densaugeo** [comment]
Looks like it IS working, but my pipx was using an old copy from cache.
