### ISSUE TITLE
Issue with systemd-journal-upload

### ISSUE THREAD

**Issue by Paiusco** [Densaugeo/uploadserver#36]
I was trying to have a simple way to start a server to upload the logs from another target using `uploadserver`. 

I can see the file being transferred and finished even, however the connection only ends when systemd-journal-upload fails with timeout. And the uploadsever crashes with following Traceback:
```
Exception occurred during processing of request from ('10.10.10.9', 48360)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 671, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\http\server.py", line 424, in handle_one_request
    method()
    result = receive_upload(self)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\APXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uploadserver\__init__.py", line 159, in receive_upload
    if 'files' not in form:
       ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\cgi.py", line 584, in __contains__
    raise TypeError("not indexable")
TypeError: not indexable
```

Any ideas?

**Comment by Densaugeo** [comment]
It looks like it got an unexpected result when parsing the submitted form. Do you have a capture of the request that was sent?

I'm unfamiliar with systemd-journal-upload. If you could post a minimal bug reporoduction with it that could help as well.

**Comment by Paiusco** [comment]
Steps to reproduce:

- Start the python server at localhost (that part you know more than me :D)
- Edit the `/etc/systemd/journal-upload.conf` to set the URL/PORT as the following example:
```
[Upload]
URL=http://10.10.10.10:1234
```
- Start the service by doing `systemctl start systemd-journal-upload`

and that should be enough to cause the issue (by default the timeout should be of 3min after the file is downloaded), so it takes some time.

**Comment by Paiusco** [comment]
I think it's not installed by default, but it seems that [here](https://fedoraproject.org/wiki/Changes/Remote_Journal_Logging) you can find the package (on Ubuntu you can also get installing `systemd-journal-remote`)

I think it does specify the `/upload` (as you can [see here](https://github.com/systemd/systemd-stable/blob/991158e8b9a6f6907ae4ea11fc61163da7936b04/src/journal-remote/journal-upload.c#L429)) because I see the file being transferred and appearing in the server side. Up to the complete size, however at some point instead of the connection being finished, it just stays there up until systemd times out. And at this point is when that Traceback appears.

I'm afraid it's not much configurable tho 😞 

[systemd-journal-upload manual](https://www.freedesktop.org/software/systemd/man/systemd-journal-upload.service.html#)
[systemd-journal-upload function that performs the upload](https://github.com/systemd/systemd-stable/blob/991158e8b9a6f6907ae4ea11fc61163da7936b04/src/journal-remote/journal-upload.c#L482)

**Comment by Densaugeo** [comment]
Interesting. That is the correct path, but it must also submit the files as form data with the correct field names. If you're able to point the upload at a proxy or something and get a log of the request, that will reveal if it is formatted correctly for uploadserver.

Looks like Fedora has a `systemd-journal-remote` package as well. When I try running `systemd-journal-upload` with this config:
```
[Upload]
URL=http://localhost:8000
```
It fails with the message "Upload to http://localhost:8000/upload failed: Couldn't connect to server", and uploadserver does not log any requests. Curl/Firefox have no trouble connecting.

**Comment by Densaugeo** [comment]
I just tried using `systemd-journal-upload` to send logs to an uploadserver instance running on another pc on my LAN, and it had the same "could not connect" error. I'm going to assume there's some other setup thing for the journal upload that needs to be done that I don't know about.

If you're able to get logs of what `systemd-journal-upload` is sending, or a simple way to reproduce the issue, then I'll take a look at this again.

**Comment by Densaugeo** [comment]
Without a good way to reproduce the bug, or logs of what request is causing the issue, I'm inclined to assume `systemd-journal-upload` is formatting its requests differently. Feel free to reopen this issue if you're able to get into the logs and find differently.
