### ISSUE TITLE
Accept `file` in addition to `files`

### ISSUE THREAD

**Issue by tjcim** [Densaugeo/uploadserver#39]
PowerShell's `UploadFile` does a POST with the content in the parameter named `file`. It would be cool if your tool accepted this as well.

I was in a rush and so I made the following changes to get it working:

```python
    if "files" not in form:
        if "file" not in form:
            return (http.HTTPStatus.BAD_REQUEST, 'Field "files" not found')

    try:
        fields = form["files"]
    except Exception:
        fields = form["file"]
```

Not sure if you are interested in this or not.

**Comment by Densaugeo** [comment]
In general I prefer to keep the API as narrow as possible.

Does Powershell have an equivalent to `curl` that will work? If so, I could include an example on the main readme.

**Comment by tjcim** [comment]
I am working with PowerShell version 5.1 and could not figure out how to get it to work without manually adding in all the boundary stuff which I am loathe to do.

But, You hit on a better strategy. I think going forward I will just download the standalone windows version of `curl.exe` and use that to upload to the server. Going to close this. Thank you!

**Comment by tjcim** [comment]
Switching to using curl instead of PowerShell.
