### ISSUE TITLE
Cannot set both --basic--auth and --basic-auth-upload

### ISSUE THREAD

**Issue by khanmenthe** [Densaugeo/uploadserver#42]
Hello,

when I set both --basic-auth and --basic-auth-upload it errors even though, according to the README.MD file, it shouldn't. 

Error:
`Cannot set both --basic--auth and --basic-auth-upload`

**Comment by Densaugeo** [comment]
Thanks for reporting the issue. I'm not sure whether the readme or the error is correct here - I'll try removing the check and see if allowing both breaks anything when I get a chance to do some testing.

**Comment by Densaugeo** [comment]
New version published - you should be able to use both auth options together now. Additionally, when both options are specified, both logins will be able to view / download files (uploading will be restricted to only `--basic-auth-upload`).
