### ISSUE TITLE
Upload from home page

### ISSUE THREAD

**Issue by madfatcat88** [Densaugeo/uploadserver#5]
It would be really nice if there's an "Upload" button on the home page instead of having to go to the /upload page.
Thank you for this useful module anyway.

**Comment by Densaugeo** [comment]
That would be nice to have.

The home page is generated by the built-in http.server module, and modifying it requires forking and modifying some of the built-in functions. I'll be doing some similar work soon to add HTTPS support, and may add this as well depending on how it goes.

**Comment by Densaugeo** [comment]
Unfortunately, modifying the home page would add more maintenance surface and would likely require updating when new Python versions are released.

Thank you for the suggestion anyway, it would have been useful if it were easier to maintain.
